# Generated by Django 4.1.5 on 2023-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paperslibros',
            name='reseña',
            field=models.TextField(max_length=2000),
        ),
    ]
