# Generated by Django 4.1.5 on 2023-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0003_paperslibros_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='tag1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='tag2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
