# Generated by Django 4.1.5 on 2023-02-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0008_reflexionesnoticias_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reflexionesPapers',
        ),
    ]
