# Generated by Django 4.1.5 on 2023-02-20 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0010_rename_related_to_reflexionesnoticias_relacionado_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflexionesnoticias',
            name='relacionado_con',
        ),
        migrations.AddField(
            model_name='reflexionesnoticias',
            name='relacionado_con_noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCategorias.noticias'),
        ),
        migrations.AddField(
            model_name='reflexionesnoticias',
            name='relacionado_con_paperLibro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCategorias.paperslibros'),
        ),
    ]
