# Generated by Django 4.1.5 on 2023-02-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0011_remove_reflexionesnoticias_relacionado_con_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflexionesnoticias',
            old_name='relacionado_con_paperLibro',
            new_name='relacionado_con_publicacionCientifica',
        ),
    ]
