# Generated by Django 4.1.5 on 2023-02-22 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0012_rename_relacionado_con_paperlibro_reflexionesnoticias_relacionado_con_publicacioncientifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='paperslibros',
            name='tag2',
        ),
    ]
