# Generated by Django 4.1.5 on 2023-02-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0013_remove_noticias_tag2_remove_paperslibros_tag2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperslibros',
            name='imagen',
        ),
        migrations.CreateModel(
            name='imagenPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='papers')),
                ('vinculado_con', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCategorias.paperslibros')),
            ],
        ),
    ]
