# Generated by Django 4.1.5 on 2023-02-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCategorias', '0014_remove_paperslibros_imagen_imagenpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperslibros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='papers'),
        ),
        migrations.DeleteModel(
            name='imagenPaper',
        ),
    ]
